name: dart_most_repeated
description: A dart lib that sorts the words in a string by the most repeated
version: 1.0.0
environment:
  sdk: '>=2.14.4 <3.0.0'
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
